// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using IdentityService.Domain;

namespace IdentityService
{
    public partial class AuthDBContext : DbContext
    {
        public AuthDBContext(DbContextOptions<AuthDBContext> options)
            : base(options)
        {
        }

        /// <summary>
        /// 权限表
        /// </summary>
        public virtual DbSet<Permission> Permissions { get; set; }
        /// <summary>
        /// 角色表
        /// </summary>
        public virtual DbSet<Role> Roles { get; set; }
        /// <summary>
        /// 角色权限表
        /// </summary>
        public virtual DbSet<RolePermissionRelation> RolePermissionRelations { get; set; }
        /// <summary>
        /// 用户角色表
        /// </summary>
        public virtual DbSet<UserRoleRelation> UserRoleRelations { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Permission>(entity =>
            {
                entity.Property(e => e.CreateTime).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Status)
                    .HasDefaultValueSql("((1))")
                    .HasComment("1启用0禁用");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.Property(e => e.CreateTime).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Status)
                    .HasDefaultValueSql("((1))")
                    .HasComment("1启用0禁用");
            });

            modelBuilder.Entity<RolePermissionRelation>(entity =>
            {
                entity.HasOne(d => d.Permission)
                    .WithMany(p => p.RolePermissionRelations)
                    .HasForeignKey(d => d.PermissionId)
                    .HasConstraintName("FK_RolePermissionRelation_Permission");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.RolePermissionRelations)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_RolePermissionRelation_Role");
            });

            modelBuilder.Entity<UserRoleRelation>(entity =>
            {
                entity.HasOne(d => d.Role)
                    .WithMany(p => p.UserRoleRelations)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_UserRoleRelation_Role");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}