// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Domain
{
    [Table("ArtCategory")]
    [Index("ArticleId", "CategoryId", Name = "IX_ArtCategory_1", IsUnique = true)]
    public partial class ArtCategory
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("categoryId")]
        public int CategoryId { get; set; }
        [Column("articleId")]
        public int ArticleId { get; set; }

        [ForeignKey("ArticleId")]
        [InverseProperty("ArtCategories")]
        public virtual Article Article { get; set; }
        [ForeignKey("CategoryId")]
        [InverseProperty("ArtCategories")]
        public virtual Category Category { get; set; }
    }
}