// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Domain
{
    [Table("ArtCategory")]
    [Index("Name", "ParentId", "UserId", Name = "IX_ArtCategory")]
    public partial class ArtCategory
    {
        public ArtCategory()
        {
            Articles = new HashSet<Article>();
            InverseParent = new HashSet<ArtCategory>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("parentId")]
        public int? ParentId { get; set; }

        [ForeignKey("ParentId")]
        [InverseProperty("InverseParent")]
        public virtual ArtCategory Parent { get; set; }
        [InverseProperty("Category")]
        public virtual ICollection<Article> Articles { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<ArtCategory> InverseParent { get; set; }
    }
}