// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Domain
{
    [Table("Article")]
    public partial class Article
    {
        public Article()
        {
            ArtCategories = new HashSet<ArtCategory>();
            ArticleTags = new HashSet<ArticleTag>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        [Column("content")]
        public string Content { get; set; }
        [Column("summary")]
        public string Summary { get; set; }
        [Column("photo")]
        [StringLength(50)]
        public string Photo { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("regionId")]
        public int? RegionId { get; set; }
        /// <summary>
        /// -1待审核1已发布2私有3回收站
        /// </summary>
        [Column("status")]
        public int Status { get; set; }
        /// <summary>
        /// -1不可以评论1可评论2需要审核评论
        /// </summary>
        [Column("commentStatus")]
        public int CommentStatus { get; set; }
        [Column("createTime", TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column("updateTime", TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 1未锁定-1锁定
        /// </summary>
        [Column("isLock")]
        public int IsLock { get; set; }

        [ForeignKey("RegionId")]
        [InverseProperty("Articles")]
        public virtual ArtRegion Region { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<ArtCategory> ArtCategories { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
    }
}