// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArticleService.Domain
{
    [Table("Category")]
    [Index("Name", "UserId", Name = "IX_ArtCategory", IsUnique = true)]
    [Index("Id", "ParentId", Name = "IX_Category", IsUnique = true)]
    public partial class Category
    {
        public Category()
        {
            ArtCategories = new HashSet<ArtCategory>();
            InverseParent = new HashSet<Category>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("parentId")]
        public int? ParentId { get; set; }

        [ForeignKey("ParentId")]
        [InverseProperty("InverseParent")]
        public virtual Category Parent { get; set; }
        [InverseProperty("Category")]
        public virtual ICollection<ArtCategory> ArtCategories { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<Category> InverseParent { get; set; }
    }
}