// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityService.Domain
{
    [Table("Permission")]
    [Index("Action", "Controller", "Service", Name = "IX_Permission", IsUnique = true)]
    public partial class Permission
    {
        public Permission()
        {
            RolePermissionRelations = new HashSet<RolePermissionRelation>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("service")]
        [StringLength(100)]
        public string Service { get; set; }
        [Required]
        [Column("controller")]
        [StringLength(100)]
        public string Controller { get; set; }
        [Required]
        [Column("action")]
        [StringLength(100)]
        public string Action { get; set; }
        [Column("description")]
        [StringLength(100)]
        public string Description { get; set; }
        [Column("updateTime", TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
        [Column("createTime", TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// 1启用0禁用
        /// </summary>
        [Column("status")]
        public int Status { get; set; }

        [InverseProperty("Permission")]
        public virtual ICollection<RolePermissionRelation> RolePermissionRelations { get; set; }
    }
}