// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityService.Domain
{
    [Table("RolePermissionRelation")]
    [Index("PermissionId", "RoleId", Name = "IX_RolePermissionRelation", IsUnique = true)]
    public partial class RolePermissionRelation
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("roleId")]
        public int? RoleId { get; set; }
        [Column("permissionId")]
        public int? PermissionId { get; set; }

        [ForeignKey("PermissionId")]
        [InverseProperty("RolePermissionRelations")]
        public virtual Permission Permission { get; set; }
        [ForeignKey("RoleId")]
        [InverseProperty("RolePermissionRelations")]
        public virtual Role Role { get; set; }
    }
}