// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityService.Domain
{
    [Table("Role")]
    [Index("Name", Name = "IX_Role", IsUnique = true)]
    public partial class Role
    {
        public Role()
        {
            RolePermissionRelations = new HashSet<RolePermissionRelation>();
            UserRoleRelations = new HashSet<UserRoleRelation>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// 1启用0禁用
        /// </summary>
        [Column("status")]
        public int Status { get; set; }
        [Column("createTime", TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column("updateTime", TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<RolePermissionRelation> RolePermissionRelations { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<UserRoleRelation> UserRoleRelations { get; set; }
    }
}