// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityService.Domain
{
    [Table("UserRoleRelation")]
    [Index("RoleId", "UserId", Name = "IX_UserRoleRelation")]
    public partial class UserRoleRelation
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("roleId")]
        public int RoleId { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("UserRoleRelations")]
        public virtual Role Role { get; set; }
    }
}