// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserService.Domain
{
    [Table("Score")]
    public partial class Score
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("reason")]
        [StringLength(50)]
        public string Reason { get; set; }
        [Column("value")]
        public double Value { get; set; }
        [Column("userId")]
        public int UserId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Scores")]
        public virtual User User { get; set; }
    }
}