// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserService.Domain
{
    [Table("UserFollow")]
    [Index("UserId", "WatchId", Name = "IX_UserFollow", IsUnique = true)]
    public partial class UserFollow
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("watchId")]
        public int WatchId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserFollowUsers")]
        public virtual User User { get; set; }
        [ForeignKey("WatchId")]
        [InverseProperty("UserFollowWatches")]
        public virtual User Watch { get; set; }
    }
}