// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserService.Domain
{
    [Table("UserScore")]
    public partial class UserScore
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("reason")]
        [StringLength(50)]
        public string Reason { get; set; }
        [Column("value", TypeName = "decimal(18, 2)")]
        public decimal Value { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserScores")]
        public virtual User User { get; set; }
    }
}