// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserService.Domain
{
    [Table("User")]
    [Index("Username", Name = "IX_User", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            UserFollowUsers = new HashSet<UserFollow>();
            UserFollowWatches = new HashSet<UserFollow>();
            UserScores = new HashSet<UserScore>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("username")]
        [StringLength(50)]
        public string Username { get; set; }
        [Column("phone")]
        [StringLength(11)]
        public string Phone { get; set; }
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        [Required]
        [Column("password")]
        [StringLength(200)]
        public string Password { get; set; }
        /// <summary>
        /// 1启用-1禁用
        /// </summary>
        [Column("status")]
        public int Status { get; set; }
        [Column("photo")]
        [StringLength(200)]
        public string Photo { get; set; }

        [InverseProperty("User")]
        public virtual UserDetail UserDetail { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserFollow> UserFollowUsers { get; set; }
        [InverseProperty("Watch")]
        public virtual ICollection<UserFollow> UserFollowWatches { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserScore> UserScores { get; set; }
    }
}