// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserService.Domain
{
    [Table("Watch")]
    public partial class Watch
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("watchId")]
        public int WatchId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Watches")]
        public virtual User User { get; set; }
    }
}