// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommentService.Domain
{
    public partial class Comment
    {
        public Comment()
        {
            InverseParent = new HashSet<Comment>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("content", TypeName = "ntext")]
        public string Content { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("articleId")]
        public int ArticleId { get; set; }
        [Column("createTime", TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 1审核通过2需要审核-1禁止评论
        /// </summary>
        [Column("status")]
        public int Status { get; set; }
        [Column("parentId")]
        public int? ParentId { get; set; }

        [ForeignKey("ParentId")]
        [InverseProperty("InverseParent")]
        public virtual Comment Parent { get; set; }
        [InverseProperty("Parent")]
        public virtual ICollection<Comment> InverseParent { get; set; }
    }
}