// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommentService.Domain
{
    [Index("ArticleId", "UserId", "Status", Name = "IX_ArtLike", IsUnique = true)]
    public partial class Like
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("articleId")]
        public int ArticleId { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        /// <summary>
        /// 0点赞1收藏
        /// </summary>
        [Column("status")]
        public int Status { get; set; }
    }
}