// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommentService.Domain
{
    public partial class View
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("articleId")]
        public int ArticleId { get; set; }
        [Column("userId")]
        public int? UserId { get; set; }
        [Column("ip")]
        [StringLength(50)]
        public string Ip { get; set; }
        [Column("viewTime", TypeName = "datetime")]
        public DateTime ViewTime { get; set; }
    }
}